version: '3.4'

services:
  dpss:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ./apps:/usr/src/dpss/apps
      - ./progs:/usr/src/dpss/progs
      - ./benchmark:/usr/src/dpss/benchmark
      - ./.benchmarks:/usr/src/dpss/.benchmarks
      - ./aws:/usr/src/dpss/aws
      - ./conf:/usr/src/dpss/conf
      - ./docs:/usr/src/dpss/docs
      - ./dpss:/usr/src/dpss/dpss
      - ./scripts:/usr/src/dpss/scripts
      - ./tests:/usr/src/dpss/tests
      - ./.coveragerc:/usr/src/dpss/.coveragerc
      - ./.flake8:/usr/src/dpss/.flake8
      - ./Makefile:/usr/src/dpss/Makefile
      - ./pytest.ini:/usr/src/dpss/pytest.ini
      - ./setup.py:/usr/src/dpss/setup.py
      - ./pairing/pypairing/__init__.py:/usr/src/dpss/pairing/pypairing/__init__.py
      - ./pairing/src:/usr/src/dpss/pairing/src
      - ./pairing/benches:/usr/src/dpss/pairing/benches
      - ./pairing/Cargo.toml:/usr/src/dpss/pairing/Cargo.toml
      - ./pairing/setup.py:/usr/src/dpss/pairing/setup.py
      - ./:/usr/src/dpss/
      - /usr/src/dpss/dpss/ntl  # Directory _not_ mounted from host
    command: pytest -v --cov=dpss
